if: (branch = master) OR (branch = develop) OR (type = pull_request) OR (tag IS present)

dist: xenial

language: node_js

node_js:
- '10'

cache:
  directories:
    - node_modules

script:
  - chmod +x ci/build_production_releases.sh

before_deploy:
  - ./ci/build_production_releases.sh

deploy:
  provider: releases
  api_key: "${GITHUB_API_KEY}"
  file_glob: true
  file:
    - ci/outputs/*-rinkeby.zip
    - ci/outputs/*-mainnet.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
